### ISSUE TITLE
Step is not working with build-for-testing output

### ISSUE THREAD

**Issue by fepersembe** [browserstack/browserstack-bitrise-xcui-step#6]
I am trying to run UI TEsts on Browserstack through Bitrise and getting failure when I did the required steps.

In the [documentation of BrowserStack](https://www.browserstack.com/docs/app-automate/xcuitest/bitrise) it says that $BITRISE_TEST_BUNDLE_PATH should be used.

When I do that I am getting the following error:

`2022/09/09 06:27:49 xcuitest_testsuite_path: couldn’t find the <AppnameUITests>-Runner.app .  Please add the $BITRISE_TEST_BUNDLE_PATH from Xcode Build for testing for iOS step or the absolute path of <AppnameUITests>-Runner.app
`

I have tried to give path of **.app** file specifically and got ZIP_ERROR with exit code 12 for that. 

This is the output of Xcode- Build-for-testing STEP

```
The xcodebuild command log file path is available in BITRISE_XCODE_RAW_RESULT_TEXT_PATH env: /Users/[REDACTED]/deploy/raw-xcodebuild-output.log
The test bundle directory is available in BITRISE_TEST_BUNDLE_PATH env: /var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/test_bundle1461532094
The zipped test bundle is available in BITRISE_TEST_BUNDLE_ZIP_PATH env: /Users/[REDACTED]/deploy/testbundle.zip
The built xctestrun file is available in BITRISE_XCTESTRUN_FILE_PATH env: /var/folders/wf/8v049ft10mx2wzww1j4v8j700000gn/T/test_bundle1461532094/Test-Dev_Run-CoreMobile-Regression_iphoneos15.4-arm64.xctestrun
```

Do you have any suggestion to resolve this issue ?

**Comment by deepwired** [comment]
We are working on a fix, its in testing, should be live in the next 3-4 working days.

**Comment by deepwired** [comment]
We have raised a PR on bitrise, waiting for them to approve and merge the PR.
https://github.com/bitrise-io/bitrise-steplib/pull/3621

**Comment by fepersembe** [comment]
@deepwired Thanks for quick action.

**Comment by fepersembe** [comment]
@deepwired It seems they expect Browserstack side to accept a CLA. Please let me know once it is merged :) I can't wait to try updated version 😬

**Comment by fepersembe** [comment]
https://github.com/bitrise-io/bitrise-steplib/pull/3621 with this PR Merged Issue is now resolved.

**Comment by Vicky-IAG** [comment]
We are still facing the same issue in `BrowserStack App Automate - XCUITest`:`Version 1.0.1`
The other step's version are as below:

- `Xcode Build for testing for iOS` : `2.1.2`
- `Xcode Archive & Export for iOS` : ` 4.7.1`

Can you reopen this issue and test it with latest Bitrise pipeline versions? @deepwired

**Comment by dvshelley** [comment]
What was the resolution of this error message? I'm getting
`xcuitest_testsuite_path: couldn’t find the <AppnameUITests>-Runner.app .  Please add the $BITRISE_TEST_BUNDLE_PATH from Xcode Build for testing for iOS step or the absolute path of <AppnameUITests>-Runner.app`

Does that mean that I'm doing something wrong? Do I need to configure something differently?

**Comment by Zemotacqy** [comment]
The source of this error resides https://github.com/browserstack/browserstack-bitrise-xcui-step/blob/a3492edb05d21f1d9cebe3cfe0979970f3cdd5ba/util_fns.go#L281-L296

As per the algorithm: An ideal dir structure for the testbundle would be:
```
/Users/manishranjan/Library/Developer/Xcode/DerivedData/BullsEye-fluxudimluchincxqxsstjrjvseb/Build/Products/
├── BullsEye_UITests_iphoneos17.0-arm64.xctestrun
└── Debug-iphoneos
    ├── BullsEye.app
    ├── BullsEye.swiftmodule
    ├── BullsEyeFailingTests.swiftmodule
    ├── BullsEyeSlowTests.swiftmodule
    ├── BullsEyeTests.swiftmodule
    ├── BullsEyeUITests-Runner.app
    └── BullsEyeUITests.swiftmodule
```
So,
- If we do not find Runner.app in `Products/Debug-iphoneos/` - The attempt error is thrown.
- If we do not have correctly named: `Products/Debug-iphoneos` - The attempt error is thrown.

It is a known caveat that some apps build dir structure may contain build variant in its name. Example: `Products/Debug-Release-iPhoneos`. In such cases, we can remove the build variant and make it work.
